name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '*'

jobs:
  test-blockdiag:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Install python 3.8.1
      uses: gabrielfalcao/pyenv-action@v10
      with:
        # we cannot use 3.8.6 because pyenv 1.2.18 does not have the "definition" of this version,
        # and thus cannot install it!
        # see: https://github.com/gabrielfalcao/pyenv-action/pull/100
        default: 3.8.1
        command: pip install -U pip  # upgrade pip after installing python
      env:
        # allow unsecure commands add-path and set-env until v7 is available
        # see: https://github.com/gabrielfalcao/pyenv-action/issues/99
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Create virtualenv for python 3.8.1
      run: pyenv local 3.8.1

    - name: Install BlockDiag
      run: make installBlockDiag

    - name: Test BlockDiag
      run: make testBlockDiag

  test-containers:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin

    - name: Install Java dependencies
      run: make installLocalDependencies

    - name: Build Java server
      run: make buildServer

    - name: Setup Docker
      # taken from https://github.com/docker/github-actions/blob/0f18e2abad9a4ac2963d2516246787375b5ec917/Dockerfile#L32
      run: curl -fL https://download.docker.com/linux/static/stable/x86_64/docker-20.10.4.tgz | tar xzO docker/docker > docker && sudo mv -f docker /usr/bin/docker && sudo chmod +x /usr/bin/docker

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build nomnoml
      uses: docker/build-push-action@v3
      with:
        context: nomnoml
        file: nomnoml/ops/docker/alpine/Dockerfile
        push: false
        tags: kroki-builder-nomnoml:alpine,kroki-builder-nomnoml:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Build vega
      uses: docker/build-push-action@v3
      with:
        context: vega
        file: vega/ops/docker/alpine/Dockerfile
        push: false
        tags: kroki-builder-vega:alpine,kroki-builder-vega:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Build wavedrom
      uses: docker/build-push-action@v3
      with:
        context: wavedrom
        file: wavedrom/ops/docker/alpine/Dockerfile
        push: false
        tags: kroki-builder-wavedrom:alpine,kroki-builder-wavedrom:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Build bytefield
      uses: docker/build-push-action@v3
      with:
        context: bytefield
        file: bytefield/ops/docker/alpine/Dockerfile
        push: false
        tags: kroki-builder-bytefield:alpine,kroki-builder-bytefield:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Build container images
      run: make buildDockerImages

    - name: 'Setup Node.js 16'
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install Node dependencies
      run: npm install

    - name: Run smoke tests
      run: make smokeTests

    # This ugly bit is necessary if you don't want your cache to grow forever until it hits GitHub's limit of 5GB.
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

