name: Publish pikchr

on:
  push:
    paths:
      - 'server/ops/docker/build-static-pikchr'
    branches:
      - main

jobs:
  publish-pikchr:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker
        # taken from https://github.com/docker/github-actions/blob/0f18e2abad9a4ac2963d2516246787375b5ec917/Dockerfile#L32
        run: curl -fL https://download.docker.com/linux/static/stable/x86_64/docker-20.10.4.tgz | tar xzO docker/docker > docker && sudo mv -f docker /usr/bin/docker && sudo chmod +x /usr/bin/docker

      - name: Publish container image
        run: make -C server/ops/docker publishPikchr
